OpenJDK 11: Merging java.lang.* trivial changes
This is a part of merging upstream changes from OpenJDK 11.28. It
updates classes with trivial changes (most of them single line javadoc
additions). The following classes were updated:

 * AbstractMethodError.java
 * ArithmeticException.java
 * ArrayStoreException.java
 * BootstrapMethodError.java
 * ClassCastException.java
 * ClassCircularityError.java
 * ClassFormatError.java
 * ClassNotFoundException.java
 * CloneNotSupportedException.java
 * Cloneable.java
 * EnumConstantNotPresentException.java
 * Error.java
 * Exception.java
 * ExceptionInInitializerError.java
 * FunctionalInterface.java
 * IllegalAccessError.java
 * IllegalAccessException.java
 * IllegalArgumentException.java
 * IllegalMonitorStateException.java
 * IllegalStateException.java
 * IllegalThreadStateException.java
 * IncompatibleClassChangeError.java
 * InstantiationError.java
 * InstantiationException.java
 * InternalError.java
 * InterruptedException.java
 * LinkageError.java
 * NegativeArraySizeException.java
 * NoClassDefFoundError.java
 * NoSuchFieldError.java
 * NoSuchFieldException.java
 * NoSuchMethodError.java
 * NoSuchMethodException.java
 * NullPointerException.java
 * Number.java
 * OutOfMemoryError.java
 * Override.java
 * Readable.java
 * Runnable.java
 * RuntimeException.java
 * SafeVarargs.java
 * SecurityException.java
 * StackOverflowError.java
 * StringIndexOutOfBoundsException.java
 * SuppressWarnings.java
 * ThreadDeath.java
 * TypeNotPresentException.java
 * UnknownError.java
 * UnsatisfiedLinkError.java
 * VerifyError.java
 * VirtualMachineError.java
 * Void.java
 * package-info.java

Bug: 198640665
Test: m droid
Change-Id: I5f294f87499f82e5ff6290e3cb5a9a1a3be701e3