Fix unclean revert in URLConnectionTest.
commit 53e5ac334368cd0d0e36a92bf2b2db9c42d32c37 didn't revert
commit 90c7f03b322867365fa1b3ab253c8d12c0277d33 cleanly in this branch,
causing

java.lang.AssertionError: expected:<[TLSv1, TLSv1.2, TLSv1.1]> but was:<[TLSv1, TLSv1.3, TLSv1.2, TLSv1.1]>

in URLConnectionTest. This fixes the revert.

Merged-In set to avoid merging where the reland
https://r.android.com/2654012 has gone in.

Test: Presubmits
Bug: 291096949
Ignore-AOSP-first: Fixes revert that was unclean in internal branches
Change-Id: If3c143eca3ec266e7ec63772c86a86c3909a5637
Merged-In: Iaaedb093f414546b681172cb35d91e26bfab0e43