Revert "Use the runtime's implementation for park/unpark"
This reverts commit f62e812bcf9b566599ff565ab469f90907fb11a6.

Reason for revert: This CL unfortunately breaks:
sdk_gphone_x86-sdk_addon_mac
sdk_mac

Following error:
art/runtime/thread.cc:370:4: warning: "LockSupport.park/unpark implemented as noops without FUTEX support." [-W#warnings]
#warning "LockSupport.park/unpark implemented as noops without FUTEX support."
^
art/runtime/thread.cc:295:24: error: unused parameter 'is_absolute' [-Werror,-Wunused-parameter]
void Thread::Park(bool is_absolute, int64_t time) {
^
art/runtime/thread.cc:295:45: error: unused parameter 'time' [-Werror,-Wunused-parameter]
void Thread::Park(bool is_absolute, int64_t time) {
^
1 warning and 2 errors generated.

Change-Id: Ifa5e6be9c73ef9b03fc6854f2087f487949ad6f7